### ISSUE TITLE
chaincode fabric SDK version

### ISSUE THREAD

**Issue by SamYuan1990** [IBM/decentralized-energy-fabric-on-IBP20#18]
Recently, I had meet problem as error log below from chaincode container after deployed to IBP 2.0.

(node:15) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
2019-05-07T08:35:00.918Z ERROR [contracts-spi/chaincodefromcontract.js]  
	{"message":"Unexpected token \u0004 in JSON at position 0","stack":"SyntaxError: Unexpected token \u0004 in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at new ClientIdentity (/usr/local/src/node_modules/fabric-shim/lib/chaincode.js:253:38)\n    at ChaincodeFromContract.invokeFunctionality (/usr/local/src/node_modules/fabric-shim/lib/contract-spi/chaincodefromcontract.js:290:35)\n    at ChaincodeFromContract.Init (/usr/local/src/node_modules/fabric-shim/lib/contract-spi/chaincodefromcontract.js:250:25)\n    at handleMessage (/usr/local/src/node_modules/fabric-shim/lib/handler.js:611:47)\n    at ChaincodeSupportClient.handleInit (/usr/local/src/node_modules/fabric-shim/lib/handler.js:352:9)\n    at ClientDuplexStream.<anonymous> (/usr/local/src/node_modules/fabric-shim/lib/handler.js:293:30)\n    at emitOne (events.js:116:13)\n    at ClientDuplexStream.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)"}

It would fixed via updated fabric sdk from 1.4.0-beta2 to 1.4.0

Before (won't work)
`"fabric-contract-api": "1.4.0-beta2",`
`"fabric-shim": "1.4.0-beta2"`

After (works)
`"fabric-contract-api": "1.4.0",`
`"fabric-shim": "1.4.0"`

Could some one take a look at?

**Comment by horeaporutiu** [comment]
@SamYuan1990 Thanks for pointing this out. I have now updated the fabric shim and fabric contract api to the latest versions (1.4.1).
