### ISSUE TITLE
I get this error when adding a resident, any help welcome!

### ISSUE THREAD

**Issue by japrsmart** [IBM/decentralized-energy-fabric-on-IBP20#20]
Submit "AddResident" transaction.
2019-05-29T00:38:58.747Z - warn: [DiscoveryEndorsementHandler]: _build_endorse_group_member >> G0:0 - endorsement failed - Error: transaction returned with failure: SyntaxError: Unexpected token  in JSON at position 0
Failed to submit transaction: Error: Endorsement has failed

**Comment by horeaporutiu** [comment]
@japrsmart yes, I have replicated the error, and am working on a fix.

**Comment by horeaporutiu** [comment]
@japrsmart I have fixed the error with the latest commits. Please git clone the latest version of the project, and try it out. The error should be gone.

**Comment by horeaporutiu** [comment]
@japrsmart Just tested and seemed to confirm this error is gone. Closing this issue now. Please do reopen if you see there is another problem with the AddResident transaction. 

Thanks again for opening this issue!

**Comment by japrsmart** [comment]
Thanks for the answer, I tried the new github files but did not work. And
the angular app does not work either when I try to add a new resident.

Jaime.

**Comment by bafu** [comment]
@horeaporutiu I can also reproduce this issue and got the same error message as @japrsmart 

```
╭─debug@bafu-mba4g256 ~/codes/decentralized-energy-fabric-on-IBP20/application/add-participants  ‹master*› 
╰─$ node addResident.js 
Wallet path: /home/debug/codes/decentralized-energy-fabric-on-IBP20/application/_idwallet

Submit "AddResident" transaction.
2020-03-17T09:07:22.540Z - warn: [DiscoveryEndorsementHandler]: _build_endorse_group_member >> G0:0 - endorsement failed - Error: transaction returned with failure: SyntaxError: Unexpected end of JSON input
Failed to submit transaction: Error: Endorsement has failed
```

**Environment**

* Node.js: 10.19.0
