### ISSUE TITLE
Reopen a closed issue - Adding a resident...error persisted with new commit...

### ISSUE THREAD

**Issue by japrsmart** [IBM/decentralized-energy-fabric-on-IBP20#22]
can you please comment on your last fix? I believe smart contract has problems when submitting a transaction. My IBM free Blockchain test network will expire in 5 days...thanks!

Submit "AddResident" transaction.
2019-05-29T00:38:58.747Z - warn: [DiscoveryEndorsementHandler]: _build_endorse_group_member >> G0:0 - endorsement failed - Error: transaction returned with failure: SyntaxError: Unexpected token � in JSON at position 0
Failed to submit transaction: Error: Endorsement has failed

**Comment by horeaporutiu** [comment]
@japrsmart did you delete your old repo, and your old IBM Blockchain + IBM Kubernetes service, and start over again?

I have been able to successfully run all of the commands by doing the following steps.

1) delete old IBM Kubernetes service, and get a new free service
2) delete old IBM Blockchain Platform service, and create a new one, that binds to the new Kubernetes service from step 1.
3) Delete and then clone the new version of the app..(just do a git clone)
4) run through the code pattern as normal. I've ran threw it a couple of times following steps 1,2 from above, and gotten everything to work. Please try these steps and let me know if you run into any problems.

**Comment by japrsmart** [comment]
Ok I didn’t start kubernetes and IBM network from scratch. Will try that.

Thanks.

**Comment by horeaporutiu** [comment]
@japrsmart no problem, keep me posted.

**Comment by horeaporutiu** [comment]
@japrsmart did you get this to work?

**Comment by japrsmart** [comment]
Unfortunately I couldn’t. I Started all over but got the same error when adding a resident. I’m not an IT or software expert so not sure what I’m doing wrong. 

Jaime.

**Comment by varunagarwal315** [comment]
@japrsmart Did you manage to fix the problem? If your IBP subscription expired, you can refer [to this issue](https://github.com/IBM/decentralized-energy-fabric-on-IBP20/issues/23) and run it locally, then go back to debugging adding a resident.

**Comment by bafu** [comment]
@horeaporutiu I can also reproduce this issue and got the same error message as @japrsmart 

```
╭─debug@bafu-mba4g256 ~/codes/decentralized-energy-fabric-on-IBP20/application/add-participants  ‹master*› 
╰─$ node addResident.js 
Wallet path: /home/debug/codes/decentralized-energy-fabric-on-IBP20/application/_idwallet

Submit "AddResident" transaction.
2020-03-17T09:07:22.540Z - warn: [DiscoveryEndorsementHandler]: _build_endorse_group_member >> G0:0 - endorsement failed - Error: transaction returned with failure: SyntaxError: Unexpected end of JSON input
Failed to submit transaction: Error: Endorsement has failed
```

Note: I can not re-open this issue because I'm not the author.

**Environment**

* decentralized-energy-fabric-on-IBP20: commit `cdd7411`
* Node.js: 10.19.0
