### ISSUE TITLE
Authentication Feature [WIP]

### ISSUE THREAD

**Issue by varunagarwal315** [IBM/decentralized-energy-fabric-on-IBP20#7]
Hey @ljbennett62 , I am working on adding authentication to the smart contracts to ensure the residents can only send coins that belong to them (as a start). This is in line with the Extending the Code Pattern as described in the `ReadMe.md` file.

Should have smart contracts and maybe a new `.js`. file to register multiple users with their wallets by end of week, wanted to know if I should do the PR (when I manage to) to the dev branch, or ask for a new one.

Wanted to run the concept by you

- Admin enrolls new users with id `R1`, `R2` and assigns certificates (instead of `user1`)

- Transaction to [add new resident](https://github.com/IBM/decentralized-energy-fabric-on-IBP20/blob/master/application/application.js) will be submitted using wallet of `R1` at which point the ID is added to the resident's schema (The `Resident` over here is the equivalent of a `participant` as used in `composer`)
```
let cid = new ClientIdentity(ctx.stub);
var resident = { id: cid.getID() }
await ctx.stub.putState('residents', Buffer.from(JSON.stringify(residents))); 
```

- At [this point](https://github.com/IBM/decentralized-energy-fabric-on-IBP20/blob/master/contract/lib/my-contract.js#L127) we can verify if the `id` match, else throw an error

- There are a couple of points I want to touch upon, that I will address once I open a complete PR

Do let me know if this is fine by you.

**Comment by ljbennett62** [comment]
@varunagarwal315 - yes that is fine - please go ahead an open a PR when you are ready. tx

**Comment by varunagarwal315** [comment]
Closing as I have made the PR.
